<?php

namespace App\Models\Back;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    use HasFactory;
    protected $fillable=[
    'name','slug'
    ];
    public function getRouteKey()
    {
        return 'slug'; // TODO: Change the autogenerated stub
    }
    public function articles(){
        return $this->belongsToMany(Article::class);
    }
}

